### ISSUE TITLE
Add option to disable: `focus morph was already seen this day -> burying the card`

### ISSUE THREAD

**Issue by kaegi** [kaegi/MorphMan#12]
First brought up in https://github.com/ChangSpivey/MorphMan/issues/11

**Comment by ChangSpivey** [comment]
stanaquil wrote:

>I think you might be in the process of editing your comment above, so I'll check back again in a bit, but to clarify:
>
>In my Sentences deck, all of the buried cards have words that are Unmature (I just double checked this). It just doesn't want to show them to me yet, probably because I recently worked on another card with the same Unmature word. If I try to unbury them in anki, it immediately re-buries them again. Is this the intended behavior, or am I missing something obvious?
>
>Thanks for the tag reminder, I hadn't thought of that, and it would certainly help.

**Comment by ChangSpivey** [comment]
Yep: [this line](https://github.com/ChangSpivey/MorphMan/blob/c94d78b309d3f27009084adbdad8f7a18ebf61ce/morph/newMorphHelper.py#L97) means `skip if we already saw that focus morpheme in this Anki session`. As a workaround you can close Anki (this resets the database for the morphemes learned today) then unbury these cards or set [this](https://github.com/ChangSpivey/MorphMan/blob/c94d78b309d3f27009084adbdad8f7a18ebf61ce/morph/config.py#L57) to false. But of course you should be able to disable the feature in the command line.

**Comment by ChangSpivey** [comment]
Sorry, setting the value will disable skipping globally.... which is too much. So currently reopening Anki is the only solution.

**Comment by stanaquil** [comment]
Just FYI, closing and reopening Anki, then unburying the cards, still doesn't work. MM appears to be immediately reburying them anyway. (It shows "new cards available," I click on "study cards," I immediately get the "congratulations, no new cards!" message.)

I also tried turning off Anki's own "bury related" cards setting, still get the same behavior.

I'll experiment with using tags or something similar to stop MM from modifying the cards, maybe that will help temporarily.

**Comment by ChangSpivey** [comment]
Try the new dev version. It has new options in the preferences dialog.
Try to disable `Skip cards with fresh vocabulary` and `skip cards if
focus morph was already seen today`.

**Comment by ChangSpivey** [comment]
For your problem, tags (with the dev version) are the right solution, because you don't want MorphMan in your own sentence deck at all.

But if the new dev version with the options doesn't help, but you want to understand the issue, you can disable some skip conditions [here](https://github.com/ChangSpivey/MorphMan/blob/bcc98e2a0ba8ac43c9a92076b5c06a72fb8ed12d/morph/newMorphHelper.py)

For example change:

```python
skipCondition2 = (isFreshVocab and skipFresh)
```

to

```python
skipCondition2 = False # (isFreshVocab and skipFresh)
```

(You will have to restart Anki after changing code)

That way you can bisect which condition is causing the burying.

**Comment by stanaquil** [comment]
Wow, you're fast! 

I downloaded the dev version, and I think the new General preferences tab is just what I needed. I actually prefer to see a new word in as many sentences as possible, for optimum reinforcement, so a global checkbox works for me.

For someone who wants to do what I was originally trying to do, change the behavior of the plug-in with respect to a specific deck, I was also able to do a temp fix to the problem last night by applying a deck restriction in the config.py file (the bolded line was my edit):

# Deck overrides can only override 'new card merged fill' options. 1st priority
deck_overrides = {
    **'Sentences':            { 'new card merged fill':False, 'next new card feature':False },**

Thanks so much for your work on this. I am already thinking of new tweaks I'd like to see - you'll have to tell me to stop if you get sick of me posting new feature requests. :-)

**Comment by stanaquil** [comment]
Also, I did try the tag solution, but it wasn't optimal for me, because my situation is actually more complicated than I originally described; I use the "Japanese(recognition)" model in a number of different decks, and the Sentences deck was the only one I wanted to change the behavior with, so that's why I experimented with going with a deck override.

**Comment by stanaquil** [comment]
I just wanted to drop back into this thread to say that the new General preferences tab is working wonderfully for me. 

For anyone else who might be reading this thread, I now find myself changing its settings regularly (hitting command-M each time to recalculate). To get the most new words, I keep all three boxes checked. When I'm feeling like I could use some easier cards with recently learned vocabulary, I uncheck the bottom two boxes but leave "comprehension" checked. If new cards that I want to learn are being reburied against my will, I uncheck "comprehension" until I've learned them. 

Thank you!!
