### ISSUE TITLE
Recalc error

### ISSUE THREAD

**Issue by wuxua** [kaegi/MorphMan#133]
I'm migrating from 2.0 to 2.1.26 and downloading Morphman from the ankiweb site. Updated stats.py to avoid the error at launch and then followed InfiniteRain's instruction to avoid the 'ModuleNotFoundError'. At first I was getting this error during recalc:

> Debug info:
> Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
> Platform: Windows 7
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2020-05-29 03:20:16
> 
> Caught exception:
> Traceback (most recent call last):
>   File "C:\Users\myname\AppData\Roaming\Anki2\addons21\900801631\__init__.py", line 14, in onMorphManRecalc
>     main.main()
>   File "C:\Users\myname\AppData\Roaming\Anki2\addons21\900801631\morph\main.py", line 443, in main
>     knownDb = updateNotes(allDb)
>   File "C:\Users\myname\AppData\Roaming\Anki2\addons21\900801631\morph\main.py", line 185, in updateNotes
>     TAG.register(tagNames)
>   File "lib\site-packages\anki\tags.py", line 41, in register
> TypeError: sequence item 6: expected str instance, NoneType found

Now after updating preferences.py with [this file](https://raw.githubusercontent.com/fqrious/MorphMan/patch-1/morph/preferences.py) the recalc goes further but gives this error at the end of the updating notes progress bar:

> 
> Debug info:
> Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
> Platform: Windows 7
> Flags: frz=True ao=True sv=1
> Add-ons, last update check: 2020-05-29 03:20:16
> 
> Caught exception:
> Traceback (most recent call last):
>   File "C:\Users\myname\AppData\Roaming\Anki2\addons21\900801631\__init__.py", line 14, in onMorphManRecalc
>     main.main()
>   File "C:\Users\myname\AppData\Roaming\Anki2\addons21\900801631\morph\main.py", line 443, in main
>     knownDb = updateNotes(allDb)
>   File "C:\Users\myname\AppData\Roaming\Anki2\addons21\900801631\morph\main.py", line 395, in updateNotes
>     mw.col.db.executemany(
>   File "lib\site-packages\anki\dbproxy.py", line 92, in executemany
>   File "lib\site-packages\anki\rsbackend.py", line 459, in db_execute_many
>   File "lib\site-packages\anki\rsbackend.py", line 471, in _db_command
> ankirspy.DBError: JSONError { info: "invalid type: map, expected a sequence" }

**Comment by SaraSmiseth** [comment]
You also need the changes from #123.
You can copy main.py from here https://raw.githubusercontent.com/kaegi/MorphMan/master/morph/main.py and replace yours.

**Comment by wuxua** [comment]
> 
> 
> You also need the changes from #121.
> You can copy main.py from here https://raw.githubusercontent.com/kaegi/MorphMan/master/morph/main.py and replace yours.

Finally got it to recalc without errors after doing this and #125. Thank you.
