### ISSUE TITLE
[BUG] Readability Analyser output file: master_freq = 0

### ISSUE THREAD

**Issue by IllIIIllI** [kaegi/MorphMan#136]
When I run MorphMan's Readability analyser using this frequency list
[jp_netflix_frequency.txt](https://github.com/kaegi/MorphMan/files/4712937/jp_netflix_frequency.txt) as a Master Frequency List I get the following output: [frequency - oregairu.txt](https://github.com/kaegi/MorphMan/files/4712931/frequency.-.oregairu.txt) (I've renamed the file from "frequency.txt" to "frequency - oregairu.txt" for uploading purposes.)

Now this if you scroll to line 2 of [frequency - oregairu.txt](https://github.com/kaegi/MorphMan/files/4712931/frequency.-.oregairu.txt), the master_freq for "病" is 0, which is peculiar because it does appear in [jp_netflix_frequency.txt](https://github.com/kaegi/MorphMan/files/4712937/jp_netflix_frequency.txt) at line 2518.

Thanks for looking into this in advance.

**Comment by lostasock** [comment]
Hi, I believe I'm having the same issue. Using either a frequency list produced by the Readability Analyser, or the same one as the issue opener is using, there is no change to the output frequency.txt. It says "master_freq 0" for all morphs.

**Comment by lostasock** [comment]
I'm running Anki 2.1.22 with the latest Morphman that's on ankiweb. With the updated stats.py from this github project.

**Comment by lostasock** [comment]
If anyone else is reading this, can you let us know if the master freq list is working for you? And which version of Anki/morphman you are using.

**Comment by lostasock** [comment]
From what I can gather, the analyser is expecting the frequency list to be in Mecab format. Not the frequency list you are using, nor one created by the analyser itself. A quick look at the code for readability.py seems that it uses the first 6 tab separated columns. Something that looks like this.
```
5101316	だ	だ	ダ	助動詞	*
3812220	は	は	ハ	助詞	係助詞
3594077	の	の	ノ	助詞	格助詞
3518316	た	た	タ	助動詞	*
3202690	に	に	ニ	助詞	格助詞
2978453	を	を	ヲ	助詞	格助詞

```

There's some information in this video https://www.youtube.com/watch?v=sZwrJdOkrYg

and here, including netflix freq lists in the right format https://letslearnjapanese.neocities.org/morphman.html

**Comment by lostasock** [comment]
From what I can gather, the analyser is expecting the frequency list to be in the same format produced by the Readability Analyser's word_freq_report.txt. NOT frequency.txt, as I was initially trying to use. Something that looks like this.
```
5101316	だ	だ	ダ	助動詞	*	1	1	4.62414401	4.62414401 matches 0
3812220	は	は	ハ	助詞	係助詞	2	2	3.45562876	8.07977277 matches 0
3594077	の	の	ノ	助詞	格助詞	3	3	3.25789064	11.33766341 matches 0
3518316	た	た	タ	助動詞	*	4	4	3.18921625	14.52687966 matches 0
3202690	に	に	ニ	助詞	格助詞	5	5	2.90311359	17.42999325 matches 0
```

There's some information in this video https://www.youtube.com/watch?v=sZwrJdOkrYg

and here, including Netflix frequency lists in the right format https://letslearnjapanese.neocities.org/morphman.html

**Comment by ianki** [comment]
@lostasock is correct, the master frequency list has to be in the format of the word_freq_report.txt

Using just a regular word list won't work.
