### ISSUE TITLE
Request: Readability Analyser - Option to Include Proper Nouns

### ISSUE THREAD

**Issue by lostasock** [kaegi/MorphMan#138]
Hi. In its current implementation, the Readability Analyser excludes proper nouns. I use the Readability Analyser to create the frequency.txt list, to order new cards by frequency. I find it more useful to have proper nouns included on this list, then whilst studying, mark them as Already Known if they are indeed already known.

**Comment by ianki** [comment]
There is already an option, under the general preferences tab.
