### ISSUE TITLE
Morphman stopped burying cards with the "K" shortcut

### ISSUE THREAD

**Issue by reinzanini** [kaegi/MorphMan#144]
While doing reps, Morphman used to bury cards if I pressed the "K" shortcut (for "AlreadyKnown"). However, after I created a new Anki profile, Morphman stopped doing this and instead just tags them and nothing more. How to fix it?

Edit: me dumb. Forgot to check "modify decks".

**Comment by CarlOlson** [comment]
Is that for new cards or learned? It only has buried on new cards for me. Learned cards only get tagged.

**Comment by Alexnder77** [comment]
I have the same problem for both new and learned cards

**Comment by CarlOlson** [comment]
Can you share your Anki version, OS, and Morphman version? And if able check if it happens with other plugins disabled? It might help track down the cause. Thanks.
