### ISSUE TITLE
Preferences do not save and instead reset to default upon confirming changes with "Apply" in GUI

### ISSUE THREAD

**Issue by RANIVACAR** [kaegi/MorphMan#149]
When trying to edit anything under Tools > Morphman > Preferences (under any of the four tabs) and hitting "Apply", no changes are saved, as evident when reopening the GUI or trying to recalculate cards.

I attempted editing the preferences.py as well. When reopening Anki and checking the Morphman preferences using the GUI there again, everything is the same default that it reverts to upon making changes there and then hitting "apply". 

Upon viewing preferences.py again afterwards, it did not revert to anything and kept my changes intact, despite the GUI resetting everything, and all other Morphman functions failing to recalculate anything in accordance with the default settings. 

In trying to troubleshoot this I found a few very recent Reddit threads asking for support on this issue, none of which had solutions in them. This may be a bug worth looking at (if myself and those who wrote those threads aren't all doing something critically wrong, of course).

**Comment by CarlOlson** [comment]
Can you list your Anki version, OS, and Morphman version? Additionally linking any related Reddit threads may be helpful. Thanks.

**Comment by SaraSmiseth** [comment]
Might be the same as #124.

**Comment by RANIVACAR** [comment]
> 
> 
> Can you list your Anki version, OS, and Morphman version? Additionally linking any related Reddit threads may be helpful. Thanks.

Windows 10, build 19041.325 64-bit
Anki 2.1.26 (70784154)
I'm not totally sure how to check for the Morphman version, but I installed it yesterday.

I was able to find more reddit threads yesterday than I can now, but:
https://www.reddit.com/r/MassImmersionApproach/comments/gljmno/morphman_preferences_arent_saving/

Ditto on having replaced stats.py to avoid the initial error.

**Comment by RANIVACAR** [comment]
> 
> 
> Might be the same as #124.

You are correct!! My apologies for not having done a better job checking. The fix listed in that thread worked for me. Thank you!!
