### ISSUE TITLE
Config not saved

### ISSUE THREAD

**Issue by MichalMichalak** [kaegi/MorphMan#151]
* Anki 2.1.26
* Morphman latest (`stats.py` overwritten from repo)
* Win 10

This is my first try to use Morphman. I open options, change tag, change card type, click "Apply" button. There's no error. A message appears telling me to recalculate db. I open options again - nothing is changed. Obviously I can't recalculate db because my card type is different and I don't use "japanese" tag, which is default.

Anyone had similar problem? How do I solve it?

**Comment by SaraSmiseth** [comment]
This is the same problem as in #124. Try the fix mentioned there.

**Comment by MichalMichalak** [comment]
Thank you, worked.
