### ISSUE TITLE
Question about the purpose of "already known" tag

### ISSUE THREAD

**Issue by ColinKennedy** [kaegi/MorphMan#156]
I'm following along a guide for morphman and am really enjoying it so far. Thank you so much for this great plugin!

Guide: https://massimmersionapproach.com/table-of-contents/anki/morphman/

In the guide, "Already known" is defined as:

```
Already known: A tag that you can manually add to notes to tell MorphMan that you already know all the Morphs contained in the note. After a Recalc, MorphMan will add all the Morphs contained in notes with this tag to the database of Mature Morphs. “K” (for Known) is the hotkey for adding this tag to a card while reviewing or in the browser.
```

My question is - what exactly are you marking as "known" when you tag something as already known?

An example scenario:

I have grammar cards with full-sentence expressions such as `子供はまだ３歳です。`
In this case, the target to learn is `まだ`. If I mark this card as already known, am I saying "I know what `まだ` means? Or am I marking "I already know what all of `子供はまだ３歳です。` means"?

**Comment by SaraSmiseth** [comment]
It depends on what the field cointains that you specified in the settings. If the field contains `子供はまだ３歳です。` then yes morphman will mark the whole sentence as known.

Your card could have the example sentence in one field and another field just for the word that you're learning. Then if you use the word field in the settings morphman will only mark the word as known.

**Comment by ColinKennedy** [comment]
That makes sense. I'm using the full sentence in the note filters so then, in that case, I'd be marking the full sentence when tagging the card with already known.

Thank you for the fast response!
