### ISSUE TITLE
Morphs not updating if focus morph field is on top position; Proper nouns and words in "()" are not skipped

### ISSUE THREAD

**Issue by YORASA** [kaegi/MorphMan#161]
Help! Ever since I've updated to the latest version to be compatible with Anki 2.22, the morphs in the focus field isn't updating. My known morphs are also not being buried/suspended and Morphman keeps on showing me morphs I already know. I think it has something to do with the database or settings. I keep on tweaking the Morphman preferences but it doesn't skip known morphs (comprehension) and proper nouns and those with "()" even if I've checked those options. I tried uninstalling Morphman and deleting my database but after I run recalc, nothing happened. 

Update: I figured out something about the focus morph field not updating. In my cards, the focus morph field is on the top of all the fields. When I switched it to 2nd field position, the morphs updates. Sadly, the proper nouns and "()" are still not skipped even though I had the "Ignore proper nouns" and "Ignore () / []" in check. What should I do about it? Thank you.

**Comment by ianki** [comment]
Please try with the latest version for Anki 2.1.35+.
