### ISSUE TITLE
MorphMan crashes anki

### ISSUE THREAD

**Issue by RandomGenerator42** [kaegi/MorphMan#163]
The issues is with morphman. When I disable the addon it doesn't crash anki. The crash happens when I am learning new words for my language. When I am reviewing old words, or any type of card not related to the language anki doesn't crash

**Comment by rteabeault** [comment]
What version of anki?
Did you get any type of error message?

**Comment by RandomGenerator42** [comment]
I have 2.1.22. No error Message just in the top bar Anki(Not Responding)

**Comment by RandomGenerator42** [comment]
I found somebody who had the exact same issue as me https://www.reddit.com/r/LearnJapanese/comments/bubd7v/morphman_decks_takes_1520_min_to_load_cards/epn6uf7/

**Comment by RandomGenerator42** [comment]
I solved the issue. I had assigned morphman to analyze a card type which I wasn't using. So i deleted it from the preferences and now everything is smooth

**Comment by RandomGenerator42** [comment]
My mistake, I celeberated prematurely. The issue is not fixed. I have no idea why it might be crashing anki.
