### ISSUE TITLE
Can't use the "L" shortcut

### ISSUE THREAD

**Issue by TonyApron** [kaegi/MorphMan#169]
So, I recently installed the add-on and everything seems to work fine, except for the L shortcut to show cards that have the same focus morph. K shortcut works. How can I fix it?

**Comment by ianki** [comment]
This seems to be working on the latest version.  Can you confirm?

**Comment by TonyApron** [comment]
Unfortunately, for me, the L command only works if I press it in the browser while a card is selected (anki looks for "target:[the target word]), but if I click on L while reviewing cards it does not work.

**Comment by TonyApron** [comment]
Okay, after deactivating the add-ons one by one I found that the command was overlapping with a command of another add-on (Life Drain), so now I fixed the problem, thanks anyway
