### ISSUE TITLE
"All note types" does not work

### ISSUE THREAD

**Issue by flo62134** [kaegi/MorphMan#171]
Hi!

I'm new to Morphman.
I encountered a bug when setting up this add-on.
The version I'm using is 2.1.

In order for Morphman to detect any card, I had to manually insert all card types like this:
![image](https://user-images.githubusercontent.com/16915877/94855522-f2983480-042e-11eb-8730-007e91ba72e0.png)

"All note types" did not work.
Without this, I ended up with the following error:

> There is no card that can be analyzed or be moved. Add cards or (re-)check your configuration under "Tools -> MorhpMan Preferences" or in "Anki/addons/morph/config.py" for mistakes.

These are my preferences:
![image](https://user-images.githubusercontent.com/16915877/94855593-10659980-042f-11eb-83a2-d29192669cc6.png)
![image](https://user-images.githubusercontent.com/16915877/94855613-15c2e400-042f-11eb-90ee-7db2d92bf815.png)
![image](https://user-images.githubusercontent.com/16915877/94855638-1bb8c500-042f-11eb-96d9-e531ec0d2fde.png)

Should there be any info missing, feel free to ask me ;)

**Comment by flo62134** [comment]
#165 should fix this issue

**Comment by ianki** [comment]
The fix was merged.  Let us know if you have more issues/
