### ISSUE TITLE
Question on deleting cards

### ISSUE THREAD

**Issue by koliviatom** [kaegi/MorphMan#208]
Do my known cards have to stay in Anki in order for Morphman to continue recognizing those words as known? Or do items in the database stay there once they are added? I'd like to delete some cards that I'm no longer reviewing but worried this will also remove those words from the all.db.

**Comment by joestrong** [comment]
Hi @koliviatom 

I saw you didn't get a reply on this. I asked a similar question previously, which I think will help you: https://github.com/kaegi/MorphMan/issues/177#issuecomment-726374893

**Comment by ianki** [comment]
Yes, cards have to stay in Anki.
