### ISSUE TITLE
Incompatibility with anki > 2.1.27

### ISSUE THREAD

**Issue by zimhat** [kaegi/MorphMan#210]
I updated anki to 2.1.35 and Morphman was deactivated by default with a message saying it wasn't supported for `anki version > 2.1.27`. It's weird since the ankiweb page says that it's compatible to `2.1.29+ (updated 2020-07-24)`.

Do I need to reinstall the addon ? I don't want to loose the database

**Comment by joestrong** [comment]
The master branch definitely works on `2.1.35`. So you can use that (but back up your database).

The ankiweb page is too out of date I'm guessing.

**Comment by zimhat** [comment]
Thanks ! The maste branch works wonderfully indeed
