### ISSUE TITLE
Installed but can't open preferences

### ISSUE THREAD

**Issue by linguax-gc** [kaegi/MorphMan#211]
Hi, I just installed the addon on lastest Anki 2.1.35.

It installed fine, but when I try to open the preferences I get an error.

Seems like it wants me to install a Japanese support plugin (it says it couldn't find the Mecab Japanese Analyzer), but I'm not going to be using it for Japanese, but for Chinese, which is supposed to be supported out of the box, I think. Do I still need to install those addons for it to work?

I can't access any MorphMan menu, all of them give the same error. I also looked into config.py but there is nothing to change there I believe.

[error.txt](https://github.com/kaegi/MorphMan/files/5649238/error.txt)

**Comment by linguax-gc** [comment]
Installing an addon including the Japanese analyzer fixed it, btw. But I'm guessing it shouldn't be a requirement if one is not going to use it for Japanese,

Thanks for your work, by the way. Very good addon!

**Comment by ianki** [comment]
Yes, I think that it currently expects to have Japanese Support installed.  We should be able to fix that.

**Comment by TonyApron** [comment]
Hi, I still have the same problem even with the fix. If I keep the mecab Japanese addon all it's fine, but if I remove it from the addon folder I can't change morphman preferences
[
[error.txt](https://github.com/kaegi/MorphMan/files/6259319/error.txt)
](url)
