### ISSUE TITLE
Release 2021.2 (2021-2-10) Readability Analyzer ImportError: libQt5WebSockets.so.5

### ISSUE THREAD

**Issue by Dranion** [kaegi/MorphMan#243]
Having a problem with ibQt5WebSockets.so.5. I don't actually use readability analyzer much but I'm pretty sure I had successfully opened it before? That said you haven't made any changes to readability.py in 24 days. The problem is probably on my end but :^) 

> Debug info:
> Anki 2.1.35 (84dcaa86) Python 3.9.1 Qt 5.15.2 PyQt 5.15.2
> Platform: Linux
> Flags: frz=False ao=True sv=2
> Add-ons, last update check: 2021-02-11 22:55:03
> Add-ons possibly involved: ⁨MorphMan for Anki 21⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/home/dranion/.local/share/Anki2/addons21/900801631/__init__.py", line 29, in onMorphManReadability
>     from .morph import readability
>   File "/home/dranion/.local/share/Anki2/addons21/900801631/morph/readability.py", line 22, in <module>
>     from PyQt5 import QtWebSockets,  QtNetwork
> ImportError: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory

Checking with pip, I have PyQt5==5.15.2, PyQt5-sip==12.8.1, PyQtWebEngine==5.15.2

**Comment by DrizztFR** [comment]
Hi there, got the exact same issue on my KDE Manjaro.

I solved it by installing **qt5-websockets 5.15.2-1**

**Comment by Dranion** [comment]
This worked for me too, thank you.

**Comment by morphpstd** [comment]
Is qt5-websockets 5.15.2-1 another Anki app? What/where is that download?
