### ISSUE TITLE
Read vs Modify?

### ISSUE THREAD

**Issue by raccrompton** [kaegi/MorphMan#247]
Apologies if the wrong place- wasn't sure where to leave this question.

I can't figure out what 'read' and 'modify' do in preferences, despite reading the helper above. Am I missing something obvious?

Perhaps it could be made clearest (at least to me) through stating what happens if:
Note / Field A is read but not write
Note / Field B is write but not read
Note / Field C is read and write

Thanks so much for building this game changing extension!

**Comment by ipasechnikov** [comment]
I may be not 100% correct but as far as I understand both types of cards will be analyzed by MorphMan. Meaning that morphemes will be extracted from selected fields, card tags like `Already Known` will be taken into consideration and so on.
But only cards that are `modify` will be reordered and MorphMan's target field will be filled.
So for example you have your core vocabulary deck and a subs2srs deck. You should keep your vocabulary deck as `read` cause you don't want to rearrange its cards to analyze them. And you should set subs2srs cards as `modify` cause you want them to be rearranged in N+1 order.

**Comment by ianki** [comment]
"Read" refers to whether or not the specified fields should be parsed by MorphMan on that model.
"Write" refers to whether or not MorphMan should update scheduling priority and set tags on that model.
