### ISSUE TITLE
Not writing focus when focus is first field of note type

### ISSUE THREAD

**Issue by hugoppp** [kaegi/MorphMan#248]
I changed my field position of the 'focus' field to be the first field of the note type.
Then I added a new deck, which had all 'focus' fields empty.
I ran recalc with modify permissions.

After that
- tags of the new cards were set, including 1T, etc. and Frequency 
- the 'Focus' field was not populated for any of the cards

Once I changed position 1 of the note type to a different field and ran recalc, the focus was being populated again.

**Comment by ianki** [comment]
Known issue, as Anki will prevent writing the 1st field if it's not unique.
