### ISSUE TITLE
After installation, can't open the Readability Analyzer

### ISSUE THREAD

**Issue by morphpstd** [kaegi/MorphMan#250]
When trying to use the Readability Analyzer for the first time after installation, I am getting this error before the Analyzer opens. Anyone know what this means?

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.9.7 PyQt 5.13.2

Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-14 23:02:19
Add-ons possibly involved: ⁨MorphMan for Anki 21⁩

Caught exception:
Traceback (most recent call last):
Library/Application Support/Anki2/addons21/900801631/__init__.py", line 29, in onMorphManReadability
    from .morph import readability
Library/Application Support/Anki2/addons21/900801631/morph/readability.py", line 22, in <module>
    from PyQt5 import QtWebSockets,  QtNetwork
ImportError: cannot import name 'QtWebSockets' from 'PyQt5' (/Applications/Anki.app/Contents/MacOS/PyQt5/__init__.pyc)

**Comment by SaraSmiseth** [comment]
This looks like #243. You probably miss QtWebSockets.

**Comment by morphpstd** [comment]
Is qt5-websockets 5.15.2-1 another Anki app? What/where is that download?

**Comment by SaraSmiseth** [comment]
On my arch linux I can install it with pacman.

`sudo pacman -Syu qt5-websockets`

It is no another Anki app. I'm not sure how to install it for windows.

**Comment by morphpstd** [comment]
Ah, I'm on a Mac if there is an option for that. Why would Morphman for Anki require a Linux software... hmmm..

**Comment by morphpstd** [comment]
This must be solvable on a Mac... anyone know how?
