### ISSUE TITLE
Should I manually fix focus field?

### ISSUE THREAD

**Issue by MichalMichalak** [kaegi/MorphMan#251]
Rarely, but it happens sometimes focus field detects wrong word. Example may be when は can be used as particle or as beginning of new word. This is not a big issue, but the question is: Should I fix the field manually? Does it do anything when I change it? Or rather I shouldn't touch that field?

**Comment by bxkx** [comment]
No use. If you change it, it'll be overwritten on the next recalc with whatever it was before you changed it. Just get more sentences so you always have a couple for every word to choose the best from.

**Comment by MichalMichalak** [comment]
I suspected it may be like this. Thanks for confirmation.
