### ISSUE TITLE
Error when trying to recalc

### ISSUE THREAD

**Issue by saitra** [kaegi/MorphMan#253]
I had no problems at all but now when I try to reclac I get this error message:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-04-18 01:26:29

Caught exception:
Traceback (most recent call last):
  File "C:\*******\Roaming\Anki2\addons21\900801631\__init__.py", line 17, in onMorphManRecalc
    main.main()
  File "C:\*******\Roaming\Anki2\addons21\900801631\morph\main.py", line 576, in main
    cur = util.allDb() if cfg('loadAllDb') else None
  File "C:\*******\Roaming\Anki2\addons21\900801631\morph\util.py", line 39, in allDb
    _allDb = MorphDb(all_db_path, ignoreErrors=True)
  File "C:\*******\Roaming\Anki2\addons21\900801631\morph\morphemes.py", line 285, in __init__
    self.load(path)
  File "C:\*******\Roaming\Anki2\addons21\900801631\morph\morphemes.py", line 328, in load
    data = MorphDBUnpickler(f).load()
EOFError: Ran out of input

I would be very grateful if you could please look into it
And thanks in advance

**Comment by triqster1** [comment]
Did you update anything? Did you try deleting all databases and recalc again? Anyways, good luck figuring this out. You will most likely get no help here. The devs (if there are still any left) don't care.

**Comment by ianki** [comment]
It looks like your database file got corrupted.  Delete the "all.db" and then retry.
