### ISSUE TITLE
Optimal order to Master Readability

### ISSUE THREAD

**Issue by yaoberh** [kaegi/MorphMan#270]
Hey all!
Could someone explain this setting? Do I understand currectly that it generates the frequency.txt in such a way that it optimizes my learning order to reach the % specified?
Thanks :)

**Comment by ianki** [comment]
This can be use to analyze multiple shows, and find the optimal order to learn the shows in.

For example if you have shows A,B,C,D, and you set a readability target for each show say 98%.  If you also set the 'Optimal order to Master Readability' to something say 95%, and also probably the 'Group By Directory' option, then then analyzer will try all the combinations and tell you what order to learn the show's in (B,D,C,A or whatever) to make the fastest readability gain.

It can take a while to process if there are many shows, but if you set a % that's not too high above where your Master Readability is currently at.

**Comment by yaoberh** [comment]
Thanks so much for the help! Understanding it now :)
