### ISSUE TITLE
Bump maximum version to 2.1.53

### ISSUE THREAD

**Issue by yaoberh** [kaegi/MorphMan#273]
There are not breaking changes in 2.1.53 to modify this.

**Comment by rwmpelstilzchen** [comment]
Does it really works without problems with 2.1.53? The [AnkiWeb page](https://ankiweb.net/shared/info/900801631) has this warning, and no update to MorphMan has been made since:

> \*\*Warning\*\*  
> Anki 2.1.50 changed a lot of things under the hood, breaking compatibility with MorphMan.  
> Use version 2.1.49 in the meanwhile: https://github.com/ankitects/anki/releases/tag/2.1.49

**Comment by yaoberh** [comment]
I didn't even see that notice! Haven't got any problems thus far, although they're probably hidden to me as I'm no expert.
Morphman does work though. Even in 2.1.54

**Comment by rwmpelstilzchen** [comment]
Good to hear :-)

I don’t need to use MorphMan at the moment¹, but when I do I will test that on my system as well. It’s not the first time a certain version of Anki breaks things with add-ons, but later versions work just fine.

¹ I avoid learning any new cards until my PhD dissertation is submitted… 📚

**Comment by rameauv** [comment]
the stats counter in the toolbar is not working. 
The link in the toolbar seems to be added with a hook ("top_toolbar_did_redraw") and the morphman preferences are loaded also via a hook ("addHook('profileLoaded', init_preferences)").
The problem seems to be that the toolbar hook is called before the preferences hook and the stats cannot be loaded.
I would like to contribute in this project if possible. Still trying to understand the code.

**Comment by rwmpelstilzchen** [comment]
Thanks, @rameauv! ^_^

**Comment by yaoberh** [comment]
That's strange about the toolbar. Working for me in 2.1.54 and it never stopped working...

**Comment by rameauv** [comment]
I'm on macos v12.3.1, with anki 2.1.54 qt5

**Comment by yaoberh** [comment]
Could be a Mac/qt5 related problem

**Comment by landonepps** [comment]
There are at least [2 known issues with 2.1.50 and newer](https://github.com/kaegi/MorphMan/labels/Anki%202.1.50).
If it works fine on your system, then feel free to [download the zip file](https://github.com/landonepps/MorphMan21/releases/tag/2022.1) and install it manually. This is the same file hosted by AnkiWeb.
To make things easier for less tech savvy users, I won't update the version on AnkiWeb until it's fully supported.

Also @rameauv we'd love to have your help! I don't have a ton of time to make contributions, right now I just work to keep AnkiWeb updated with whatever contributions the community (mainly ianki, recently) makes.

**Comment by rwmpelstilzchen** [comment]
I finished writing my dissertation, so I can relax a bit my Anki ‘abstinence’ and check MorphMan. So far, I encountered no problems with [this version](https://github.com/landonepps/MorphMan21/releases/tag/2022.1) on Anki version ⁨2.1.54 (`b6a7760c`)⁩ running on Linux.

**Comment by rwmpelstilzchen** [comment]
Well, there are problems with the v3 scheduler (#276), but this seems unrelated to the version of Anki. I tested this on both 2.1.49 and 2.1.54, with the same results: MorphMan’s automatic skipping works on v2 but not on v3.

**Comment by Vilhelm-Ian** [comment]
The fact that morphman dosen't automatically skip words is not a problem. You can just press ctrl+M to manually skip

**Comment by rwmpelstilzchen** [comment]
> The fact that morphman dosen't automatically skip words is not a problem. You can just press ctrl+M to manually skip

This should be done automatically. Doing so manually is unnecessary and laboursome.

**Comment by rameauv** [comment]
@rwmpelstilzchen I made a pull request to fix the bug I talked about. This bug is also referenced here https://github.com/kaegi/MorphMan/issues/262

**Comment by landonepps** [comment]
AnkiWeb is officially updated to the new v5.0 alpha.
https://github.com/kaegi/MorphMan/releases/tag/v5.0-qt6-alpha.1
Thanks @rameauv for the toolbar fix.
