### ISSUE TITLE
2.1.55 QT6 problem

### ISSUE THREAD

**Issue by yaoberh** [kaegi/MorphMan#278]
```
When loading '⁨Morphman for Anki 2155⁩':
⁨Traceback (most recent call last):
  File "/home/yaoberh/pyenv/lib/python3.10/site-packages/aqt/addons.py", line 247, in loadAddons
    __import__(addon.dir_name)
  File "/home/yaoberh/.local/share/Anki2/addons21/1032435232/__init__.py", line 99, in <module>
    main()
  File "/home/yaoberh/.local/share/Anki2/addons21/1032435232/__init__.py", line 47, in main
    morphmanSubMenu = QMenu("MorphMan", mw)
TypeError: arguments did not match any overloaded call:
  QMenu(parent: QWidget = None): argument 1 has unexpected type 'str'
  QMenu(str, parent: QWidget = None): argument 2 has unexpected type 'AnkiQt'
⁩
```

**Comment by kadedraven** [comment]
Also doesn't work for me with 2.1.55 QT5

**Comment by rltim151** [comment]
can confirm not working on anything above 2.1.49 
no 2.1.54
no 2.1.55 QT5 or QT6

**Comment by landonepps** [comment]
Does this release fix the issue for you?
https://github.com/kaegi/MorphMan/releases/tag/v5.0-qt6-alpha.1

**Comment by kadedraven** [comment]
Currently working with the latest 2.1.55 release using your update. Thank you so much!On Jan 8, 2023, at 14:26, Landon Epps ***@***.***> wrote:﻿
Does this release fix the issue for you?
https://github.com/kaegi/MorphMan/releases/tag/v5.0-qt6-alpha.1

**Comment by kyushuadamu** [comment]
This combination is working for me:

kaegi/MorphMan tag: v5.0-qt6-alpha.1 (qt6-migration branch)
Anki ⁨2.1.55 Windows Qt6
ianki/MecabUnidic 3.1.0 (installed from MecabUnidic3.1.0.ankiaddon file)

@landonepps thank you for updating things to work in Qt 6!
