### ISSUE TITLE
Adding support for Mandarin Chinese

### ISSUE THREAD

**Issue by cdagnino** [kaegi/MorphMan#28]
Hi,

I think it'd be nice to have support for Mandarin Chinese cards.
In the ReadMe it says:

> more languages can be added on request if morpheme-splitting-tools are available for it

Does it mean there must be morpheme splitting tools already available in `Anki` or just morpheme splitting tools in general?
I think [Chinese support](https://ankiweb.net/shared/info/3448800906) splits morphemes.

If you can explain what exactly is needed (or point to the part of the code that would need to be changed) I could try making a head start.

**Comment by kaegi** [comment]
It is actually possible. See the [Jieba-Morph](https://github.com/NinKenDo64/Jieba-Morph)-fork NinKenDo64 and I created together.

Currently I'm not actively developing MorphMan (collecting todos until I get back to it), but I might distribute it alongside the normal MorphMan later. This issue can remain open until then.

**Comment by cdagnino** [comment]
Great, thanks for the link!

**Comment by agerhbour** [comment]
Any plans on a similar branch for MorphMan21?

**Comment by davidgaya** [comment]
Chinese is supported now very well.
@shanrauf this issue should be closed.
