### ISSUE TITLE
Adding support for Anki 2.1 (Python 3 and Qt5)

### ISSUE THREAD

**Issue by landonepps** [kaegi/MorphMan#29]
MorphMan in its current state doesn't work with the Anki 2.1 beta. I ported it to work with Python 3 and Qt5, but there are a few changes in Anki itself that make conversion a little more difficult.

Here's my fork: https://github.com/landonepps/MorphMan21

I haven't been able to get keybindings to work, and I also wasn't able to get the feature to study the selected cards in the browser working. I personally never use them, so I just commented those sections out, and have been using the extension without those features.

If someone who is more familiar with Python/Anki add-on development can help out, I'd really appreciate it.

I believe that everything else works as expected. Although I only use a few of the features regularly, so more testing is needed.

**Comment by kaegi** [comment]
Nice!

I wanted to replace the "study now" feature with a different version that uses tags/a fixed due number, so this can be worked around (although with a slightly different behavior). I don't know about the keybindings though...

Your fork looks very good, but I will use Anki 2.0 until Anki 2.1 gets released (for packaging reasons) - merging is difficult until then.

**Comment by landonepps** [comment]
Yeah, I looked into making a version that was compatible with both 2.0 and 2.1, but it seemed like too much work. I also didn't test Chinese at all.
I didn't expect you to merge my fork, but I think it might be a good reference point for when MorphMan eventually needs to be updated. If you want help when that day comes, let me know.

On a side note, is there a reason you don't upload MorphMan to AnkiWeb?

**Comment by kaegi** [comment]
> On a side note, is there a reason you don't upload MorphMan to AnkiWeb?

Not really. In the beginning this was only a small fork, which didn't really "deserve" its own AnkiWeb entry, so I didn't create one. Since then I've just never looked at AnkiWeb/how to register a plugin.

**Comment by krassowski** [comment]
@kaegi It would be great to have this add-on for Anki 2.1 and in the AnkiWeb. In the AnkiWeb you can upload two separate files (zip folders with code) for Anki 2.0 and for Anki 2.1; therefore it would be easy to merge a pull request, after creating a separate branch (e.g. anki-2.0) for the old version.

To register a plugin, just go to login to AnkiWeb, and go to the https://ankiweb.net/shared/upload page.
You can find more information in the add-on creation tutorial/documentation: https://apps.ankiweb.net/docs/addons.html#sharing-add-ons.
