### ISSUE TITLE
Morphman Roadmap

### ISSUE THREAD

**Issue by mortii** [kaegi/MorphMan#299]
This would be better placed in discussions, but It's not activated for the repo. Anyway, here are my thoughts on some potential next steps for the project:
1. This is pretty trivial but the ‘.ankiaddon’ file uploaded to ankiweb only needs to contain ‘\_\_init\_\_.py’ and the ‘morph’-folder, not the entire git repo if we don't care about being able to share it outside of ankiweb.
2. If there are any repo permisson problems on github due to having an absent owner then we should just migrate to a fork and replace the readme with a link to said fork.
3. [The Refold MorphMan Addon Guide](https://web.archive.org/web/20201220134610/https://massimmersionapproach.com/table-of-contents/anki/morphman/) is stunningly good, and we should ask them if we can use it in our official guide. As for the official guide we could use something like mbook and host it for free with Github Pages, e.g. [rustup guide](https://rust-lang.github.io/rustup/installation/index.html). In addition to the Refold guide it could maybe also contain: changelog, known problems, roadmap/todos, list of contributors. We can then link to this in ankiweb and declutter the description there.
5. The 'Browse' actions either don't work or have some less than ideal implementations. I think the L’ -key should bring up ‘vocab cards' i.e. i+1 cards that you can learn immediately instead of all cards with the same focus morph. Showing all cards with the same focus morph should be moved to a different key like 'A'.
The actions are also hidden in the 'Edit' menu, maybe there is a technical reason for this but it would be infinitely better to have it in a separate 'Morph' menu, and it would also be especially useful to see the actions on the cards' right-click context menu if feasible.
6. There should be a setting to automatically 'recalc' before sync happens or something to that affect, it's so easy to forget when you have to do it manually. 
7. The codebase is a hot mess of inconsistencies and inefficencies. 
    1. The preferences.py and config.py files stand out to me as particularly insane, the hardcoded deck overrides in the bottom of config.py is absolutely criminal. Everything in config.py should be made public facing by moving them to the preferences gui. 
    2. We should introduce a mypy config file and then gradually increase its strictness as we add type annotations to the codebase.

Thoughts @landonepps ?

**Comment by mortii** [comment]
Update on the 3rd point:
I reached out to the author of the MIA guide (Matt Vs Japan), and he gave us permission to use the material!  I told him we would put the following credits at the start of the guide: "A huge thank you to Matt Vs Japan ([Youtube](https://www.youtube.com/@mattvsjapan), [Twitter](https://twitter.com/mattvsjapan)) for his absolutely amazing work on the original version of this guide!"

I have a working skeleton over on my ['website' branch](https://github.com/mortii/MorphMan/tree/website), and its Github Pages are live here: https://mortii.github.io/MorphMan/

I'll start fleshing it with the MIA guide soon.

**Comment by Raytracer42** [comment]
Are there any plans to fix issues mentioned in #290 ?

UPD. It was actually alredy fixed

**Comment by mortii** [comment]
@FilinMX The issue tracking is messy right now, but I'll go through the backlog once I finish making the guide.

**Comment by mortii** [comment]
Update:

I am almost completely done with the guide! (preview: https://mortii.github.io/MorphMan/)

Writing guides for broken features felt pretty nonsensical and unsatisfying so I made some changes to the code too:
- I implemented the things I mentioned in the 4th point of my original post, so "Learn Card Now" and the other browser actions now works. I decided to prune the obsolete features like mass tagging since that is now a native Anki feature.
- Fixed morph highlighting to actually match unmature, know, etc.
- Changed the toolbar to U: 0 A: 0 instead of K0 V0 to make it more intuitive, also added better descriptors for when you hover over or click them.
- I updated the stats page to match the new toolbar
- fixed a bunch of misc bugs 


The parts of the guide that are missing that I need some inputs on are:
- Known problems
	- Some of the 80+ issues can be closed, but I don't have the permissions to do so. If I were to go through them It will probably just become more chaotic. Could I get permissions to close issues?
- Contributors
	- I'm thinking a chronological list of git commit authors, but the master and the qt6 branch had diverged so that might be a problem. Could they be merged?

I also haven't filled in the changelog section yet, but it should be pretty straight forward.

**Comment by mortii** [comment]
After some consideration I have decided to stop working on MorphMan and publish my own fork ([AnkiMorphs](https://github.com/mortii/anki-morphs)) instead.
