### ISSUE TITLE
mm_tooLong is broken

### ISSUE THREAD

**Issue by grenzionky** [kaegi/MorphMan#30]
In sentences that I would consider to be a perfect i+1 sentence (「あなた達がいる場所は　私有地よ。」 for 私有地) it gives me the tag mm_tooLong. It also gives me too long for "これも計算のうちさ。"!!!! Which is crazy because this is barely two words....

All of the sentences that don't have the too long tag (and do have the vocab (mm_vocab) while simultaneously not having the bad length tag (mm_badLength)) are ridiculously tiny (e.g. "すぐ済む" or "切れない").

Why is that, or rather, what counts as as too long/bad length? (and how do I filter out tiny 'sentences')

**Comment by izik1** [comment]
Saw this by chance after reading Matt vs Japan's thing on this, look for [lines 48 & 49 of morph/config.py](https://github.com/kaegi/MorphMan/blob/2c13557f4d47c070a9ef0cc9bb3eeee24c62df22/morph/config.py). The default min-length is 2, and the default max-length is 8.

**Comment by IamMeWasTaken** [comment]
Those settings dont work at all those. I even put it to 10 and it still recommend "そうだよ" as the best sentence in my entire collection (K~2400). This isnt i+1 learning this is 0+1 learning. The sentences are so tiny that previous knowledge can't apply.

I am wondering if I should open another ticket for the not functioning config.py or not.

**Comment by kaegi** [comment]
The relevant code is here:

https://github.com/kaegi/MorphMan/blob/2c13557f4d47c070a9ef0cc9bb3eeee24c62df22/morph/main.py#L222-L224

https://github.com/kaegi/MorphMan/blob/2c13557f4d47c070a9ef0cc9bb3eeee24c62df22/morph/main.py#L271-L275

It should be working as expected.

**Comment by kaegi** [comment]
`Bad length` does not seem to be used anymore.

**Comment by IamMeWasTaken** [comment]
this seems to be the version for 2.1? Or is there a Min AND Max length value in the 2.0 verion I missed? All I found was a single value that is used +/-2.
