### ISSUE TITLE
external.db when learning japanese and a spaced language?

### ISSUE THREAD

**Issue by sayonaroo** [kaegi/MorphMan#32]
so I watched mattvsjapan's video and i got how you add to external.db but when you save it you have to choose SPACED language or JAPANESE. I ended up choosing spaced because that's more important than Japanese for anki but I was just wondering if there's a way to manage it SO I CAN have external.db for japanes and spaced languages??? or is my only choice to have an external.db for japanese OR spaced languages but not both.

I would think if I save japanese text under spaced language for external.db, i'm not getting the full benefit of morphman.

**Comment by sayonaroo** [comment]
https://www.youtube.com/watch?v=cOCisbsnYJs
matt vs japan video for anyone else who wants to learn how to make an external.db

**Comment by shanrauf** [comment]
Currently, the best solution is to have a separate profile per language you are using Morphman with (it seems to be the most practical solution, as opposed to adding functionality where users specify which language their deck is for).

**Comment by IllIIIllI** [comment]
> Currently, the best solution is to have a separate profile per language you are using Morphman with (it seems to be the most practical solution, as opposed to adding functionality where users specify which language their deck is for).

> it seems to be the most practical solution

This is not very conducive for people on mobile, etc, as it is very difficult to switch between profiles on mobile. I would greatly appreciate if someone could make a patch which specifies which language their deck (maybe it could even be tag based) is for.

https://www.reddit.com/r/Anki/comments/c8zvx1/is_there_a_way_to_run_morphman_to_have_separate/

I'd try to help myself if I was a better programmer, sorry.
