### ISSUE TITLE
MorphMan shows new cards with fresh vocabulary, even though "Skip cards with fresh vocabulary" is checked

### ISSUE THREAD

**Issue by ImCruel** [kaegi/MorphMan#35]
MorphMan shows new cards with fresh vocabulary although "Skip cards with fresh vocabulary" is checked and the database has been recalculated.

Edit: This only happens in Notes in which a tag specification was added (which is being ignored as well).

**Comment by Admasnd** [comment]
This also happens to me with new comprehension cards.

**Comment by shanrauf** [comment]
@Admasnd The v2 scheduler doesn't work currently with Morphman 2.1
