### ISSUE TITLE
Preferences: spaces between field names

### ISSUE THREAD

**Issue by galantra** [kaegi/MorphMan#38]
I tried separating the fields in the preference screen like this: "Front, Back, Extra".
When recalcing however, the dialogue displayed that it could not find field " Back" (note the space!).
Then I went to the preferences screen again. The field list was now shown as "Front,  Back,  Extra", with one space more behind each comma. This extra space is added every time I close the preferences window by clicking "apply".
Upon recalcing, it would then show that "  Back" or "   Back" or "    Back" (etc.) could not be found, respectively.

The only case where I get everything working is when I separate the fields by comma only, like "Front,Back,Extra". Now I'm afraid of reopening the preferences because this will add a space after each comma and deleting them manually is very cumbersome.

**Comment by galantra** [comment]
Sad to see you've closed it. I would have appreciated a short explanation.

**Comment by shanrauf** [comment]
@galantra I closed it because there was a PR a few months ago addressing this issue of multiple fields in the preferences menu. Are you still running into issues with it? https://github.com/landonepps/MorphMan21/issues/30
