### ISSUE TITLE
Converting multiple subs with Adaptive Subs

### ISSUE THREAD

**Issue by Jetbuzz** [kaegi/MorphMan#39]
First things first, thanks for getting the Adaptive subs to work. I was breaking my head over how to get it working on 2.0- to no avail.
I think Adaptive subs is one of morphman's best features as it allows an efficient way to improve your listening- while still helping grow your vocab, as you can quickly look up unknown words off subs.

I have one issue though- converting subs individually takes way too long. Is there a way to convert multiple (200+ subs)?

**Comment by kaegi** [comment]
I've never touched that part of the code, so unfortunately I can't help you. I'm not actively developing MorphMan anymore. Pull requests are welcome! A maintained 2.1 fork is https://github.com/landonepps/MorphMan21/.

**Comment by Jetbuzz** [comment]
> I've never touched that part of the code, so unfortunately I can't help you. I'm not actively developing MorphMan anymore. Pull requests are welcome! A maintained 2.1 fork is https://github.com/landonepps/MorphMan21/.

I just tried using the adaptive subs again, and it surprisingly DOES do multiple subs at a time- not sure why it didn't work before haha

The modified subs are working quite well- it can certainly be improved like ignoring names/ things written in (brackets). Many subs have names of the character written w/ each dialogue like (鈴木）もう帰ろ　
So you end up seeing the line even if you know a simple sentence.  I'm individually anki-ing some sentences with the character names before preparing subs for the whole show, but that's definitely convoluted. 

I'll try asking this in the landonepps's fork
