### ISSUE TITLE
Consider asking GitHub staff to "unfork" this repo from jre2/JapaneseStudy

### ISSUE THREAD

**Issue by izik1** [kaegi/MorphMan#42]
Some GitHub features (like searching) have had a history of not working on forks, this repo is a hugely different beast than jre2/JapaneseStudy with seemingly largely differing goals, and even different names.
Additionally, jre2/JapaneseStudy has been unmaintained since 2014.

See https://stackoverflow.com/a/27718433 for possible guidance on doing so.

**Comment by kaegi** [comment]
I have issued a request on the GitHub Support page.

**Comment by kaegi** [comment]
Wow, the GitHub Support people are FAST. Already done after 10 minutes.
