### ISSUE TITLE
what type of cards work best with this add on?

### ISSUE THREAD

**Issue by enchantednatures** [kaegi/MorphMan#47]
no where in the documentation does it mention if the cards for this add on should be complete sentences or single words and phrases.

**Comment by shanrauf** [comment]
@enchantednatures From Matt vs Japan's blog post (linked in the README of this repository):
`MorphMan is useful for use with subs2srs collections, as it can do the work of finding all of the 1T sentences in an episode for you. It is also ideal for learning with a pre-made deck alongside sentence mining, as any material contained within the pre-made deck that you’ve already learned through mining will automatically be skipped, saving you time`

Sentences are ideal when using Morphman, but there are still cool things you can do with single word/phrase cards depending on what you do.
