### ISSUE TITLE
[Feature request] Extend Learn Now with Tag, Hotkey, or option for showing manually added vocab cards first

### ISSUE THREAD

**Issue by weirdalsuperfan** [kaegi/MorphMan#49]
By default, when you create a card and add it to the deck, Anki seems to always add it to the very bottom of your deck (end of the learning queue). For creating sentence cards from definitions of cards you're currently studying (the process Matt (vs Japan) outlines in his monolingual transition video that I'm sure you're familiar with), it's necessary that I create some cards in the middle of a session, and then learn them immediately before continuing. It's fine if this ends up pushing some new cards I otherwise would've learned that day to the next day. 

However, this process currently requires that after creating the card, instead of being able to just breeze along with learning and have the card show up automatically, I have to take the additional step of going in to the browser, finding the card, and then moving it to the top of the deck/learning queue. This is ridiculous (especially since it means I might as well have created the card in the browser instead of the edit/add card window).

In order for these cards to show up at all, I currently mark them with the mm_vocabcard (or i+1 / 1T) tag.

If it would be straightforward to do, could you make a new tag for "preferential" cards that will show those cards before all others? Morphman already has the Learn Now hotkey for the browser, so I feel like this is doable. So like, maybe I could just add mm_vocab and mm_preferred to cards I make in the add/edit window, and then immediately upon adding them they show up, mimicking the behavior of moving them to the top of the deck. A hotkey or setting would work too, but I think the tag is probably best.

**Comment by shanrauf** [comment]
I looked into this for a while, but I can't find a way to add the sort of functionality you are requesting that is not overly complex. TL;DR it's definitely possible, but it seems too complex to be worth it (from what I can tell).
