### ISSUE TITLE
Differentiate same morpheme with different gramatical uses in Focus field

### ISSUE THREAD

**Issue by heitorvrb** [kaegi/MorphMan#50]
(I'm using the MeCab Dict morphemizer)

I thought Morphman was crazy, giving me Vocab notes with morphs that I already knew, but the fact was that they were different morphs. Some examples:

大変（形状詞）is different from 大変（副詞）
そう（様態）is different from そう（副詞）
etc.

But when I hit L to search for cards with the same Focus morph, it does a simple search, so it searches all そう, and it shows my card with the AlreadyKnown tag while serving me other card with (apparently) the same morph.

I could only find out what was happening by using the "View Morphemes" feature for each card, since I can't really differentiate this morphemes from the browser.

Suggestion: include a field for "part of speech of the focus morph". That field would be populated the same way the "View Morphemes" is, but only for the focus morph. That way it becomes filterable in the browser.

**Comment by shanrauf** [comment]
Done. The feature works exactly like the Focus field, only it is populated with the focus morph's part of speech (which now allows you to search by part of speech in the browser). Let me know if you find any problems.

NOTE: Ankiweb is out of date and will be for a while, so download the addon from Github. @heitorvrb
