### ISSUE TITLE
Don't remove focus morph word after recalc

### ISSUE THREAD

**Issue by juligreen** [kaegi/MorphMan#72]
Hey :)

I want to use the focus morph field even after having learned the word (I even use it on the front side on some cards) but Morphman removes the content of the focus morph field after the card is fresh or learned.

Is there an option to keep the contents of the focus morph field?
If not, could one be added?

**Comment by shanrauf** [comment]
@juligreen We fixed this recently I believe, but it simply hasn't been updated on Ankiweb (and probably won't be for a while). Try downloading Morphman from Github and let me know it if is actually fixed (I know some others were having this issue).

**Comment by juligreen** [comment]
Thank you, I will test the current Github master and reply here if everything works as expected :)

**Comment by juligreen** [comment]
This did the trick, thanks a lot for the amazing work you do!
