### ISSUE TITLE
Can you please add Thai support?

### ISSUE THREAD

**Issue by B3nGB** [kaegi/MorphMan#90]
https://pypi.org/project/thai-segmenter/

I found this project that segments Thai sentences into their words.
I just tried it and it works fine.

Would it be possible for you to add it? I would do it myself but I dont know much python and I dont know what to change/add.

Thanks

**Comment by BenGB98** [comment]
Anybody? I am willing to pay.

**Comment by shanrauf** [comment]
I was already planning on adding Thai support this week - I should have responded to your message.
