### ISSUE TITLE
Cannot Recalc after upgrade

### ISSUE THREAD

**Issue by yiufung** [kaegi/MorphMan#95]
After clicking "Check for Updates" and update all plugins (including MorphMan), I deleted all dbs under `dbs` directory, and try to do a clean Recalc. This error show up:

```
There is no card that can be analyzed or be moved. Add cards or (re-)check your configuration under "Tools -> MorhpMan Preferences" or in "Anki/addons/morph/config.py" for mistakes.
```

The error message is mysterious to me, because I have not changed any settings (`config.py` remains unchanged), and there are indeed notes in the note filters I specified:

![image](https://user-images.githubusercontent.com/1023375/75801960-ed023f80-5db6-11ea-8ba4-03d55ad9569b.png)

![image](https://user-images.githubusercontent.com/1023375/75802087-18852a00-5db7-11ea-8b2e-3e2c8b289485.png)

![image](https://user-images.githubusercontent.com/1023375/75802313-82053880-5db7-11ea-8995-4a1bd0eedfc1.png)

![image](https://user-images.githubusercontent.com/1023375/75802131-2a66cd00-5db7-11ea-9e6f-3d98dbbbce47.png)

![image](https://user-images.githubusercontent.com/1023375/75802146-3488cb80-5db7-11ea-9d2e-5dd6edcfdfe4.png)

My system info: 

```
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Linux
Flags: frz=True ao=True sv=1

Add-ons:

ImageResizer
Quick note and deck buttons Fork for 21
MeCab UniDic Japanese Dictionary
Image Occlusion Enhanced for Anki 21 alpha
Browser Resizer
Syntax Highlighting for Code
Night Mode
Autosync 21
AnkiConnect
Progress Bar (disabled)
Button Colours Good Again
Japanese Support
Replay buttons on card
Word Query
Advanced Browser
MorphMan for Anki 21
True Retention by Card Maturity
Japanese Pronunciation  Pitch Accent
Cloze Overlapper
Review Heatmap
```

Any pointers on how this may occur?

**Comment by yiufung** [comment]
On another machine where I have a working MorphMan installed from AnkiWeb, I can reproduce the problem by updating MorphMan to latest version. 

```
Anki 2.1.15 (442df9d6) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=False ao=True sv=1

Add-ons:

MeCab UniDic Japanese Dictionary
Image Occlusion Enhanced for Anki 21 alpha
Night Mode
Autosync 21
AnkiConnect
Maximum image height in card editor
Button Colours Good Again
Japanese Support
Word Query
Advanced Browser
MorphMan for Anki 21
Cloze Overlapper
Review Heatmap
```

This time I save a backup of working MorphMan under `Anki2/addons21/900801631/`. Perhaps it could help with debug. 

[morphman.tar.gz](https://github.com/kaegi/MorphMan/files/4284712/morphman.tar.gz)

Although when I try to put back the files, the addon won't start again, with Anki reporting some error. Perhaps I cannot directly replace files and expect Anki to correctly load it. Is there any change a `.colpkg` file corresponding to this version is available somewhere?

**Comment by yiufung** [comment]
Yet another trial: For Linux installation, upgrading from `2.1.15` to `2.1.20` shows the same error.

**Comment by davidgaya** [comment]
You can try creating a new profile, entering again the Morphman preferences and reimporting the Decks.

**Comment by yiufung** [comment]
@davidgaya Thanks for the suggestion. I did try to create a new profile, and import a deck for test. No luck though.

**Comment by Geniusssmit** [comment]
> @davidgaya Thanks for the suggestion. I did try to create a new profile, and import a deck for test. No luck though.

Update anki to 2.1.20

**Comment by yiufung** [comment]
@Geniusssmit Tried already. See the comment above.

**Comment by EiEiO11490** [comment]
I also have an error on windows ten after updating the app and can not recalc telling me to check the addon and make sure it is updated or check the config.py

**Comment by EiEiO11490** [comment]
@yiufung I had a similar problem. to fix it go to your morphman preferences and change the setting to the all notes type to the note type of the deck you are trying to recalc and click apply. it fixed the problem for me. may fix it for you.

**Comment by yiufung** [comment]
@EiEiO11490 Thanks, I can recalc after I setting it to the exact note types, by adding a few more entries. However, the number recalced is a lot less than before, which is quite a dismay. But it's good to know the possible cause: *handling of note types*. 

I think I'll keep remoting into my sole machine with a working Morphman before a fix comes up. Thanks for your suggestion.

**Comment by kanjieater** [comment]
Confirmed the All Note Types in the drop down seems to be broken. You need to specify which note types explicitly due to this bug.

**Comment by yiufung** [comment]
@kanjieater I fix the All Note Types for the rule I intended to Modify, now the number of morphemes are the same. Thanks for the confirmation and hint.  

![image](https://user-images.githubusercontent.com/1023375/76703171-9e379c80-670a-11ea-9e1a-29ac0ae3f032.png)
