### ISSUE TITLE
[Feature request] Add support to manage frequency lists

### ISSUE THREAD

**Issue by p2635** [kaegi/MorphMan#96]
It would be good to have a simple section in settings to manage (add / remove) frequency lists so we don't have to go hunting for the db folder and copy paste the frequency list there.

**Comment by shanrauf** [comment]
Good idea. I'll work on getting something like that within a week or two.

**Comment by lostasock** [comment]
+1

I'm often changing between different frequency lists depending on what book I'm reading. Having a list would make it easier to switch between.

Not sure how well it would work, but I'm kind of imagining a list with checkboxes where you can select zero or more frequency lists. Depending on what you've selected, the lists are added together to make a compiled frequency list. Maybe that's a bit beyond the scope of p2635's request, but I think it could be useful. That being said, being able to choose a file or collection of files in the readability analyser would achieve similar functionality. Though maybe some people aren't creating the frequency lists themselves with the readability analyser.

**Comment by IAmHughes** [comment]
This would be great to have. Additionally, where can I find a `frequency.txt` file for my language? For Spanish for example?
